### PR TITLE
move babel to devDependencies

### PR DESCRIPTION
**Pull request by nename0**
I think it doesn't make any sense to install babel, when you don't need it to run the plugin.

### CODE REVIEW

**Comment by nename0** [comment]
Yeah this doesn't work cause of the `install` script. You shoud probably take an exmple how j[uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/package.json) does it.

**Comment by nename0** [comment]
Using this package.json I was able to run `yarn build` then `yarn publish` to a local registry. The package then contained the compiled `main.js`, so when installing in an other project no need for babel.

**Comment by van-nguyen** [comment]
Hi @nename0 thanks for the PR, actually there is a need for babel to be in dependencies rather than dev. This is to support as many Node.js version as possible babel will detect the system version and compile accordingly. This might not be an idea solution, I'm open to suggestions.

**Comment by G-Rath** [comment]
@van-nguyen I'd say the ideal solution is to just target the lowest version of node you want to support, and build for that.

There's no real gain in building the plugin when it's installed vs when it's published, as the only gain would be performance *if* there was some ground-breaking speedy feature only supported in higher versions of node (which there are not).

Ultimately, any minor performance gained by using arrow functions & template strings when in an environment that supports them (not that they do give a performance boost - I'm just using them as 
 an example of common ES6 features that are only in later version of node) are lost having to spend time install the babel peerDependencies (since each CI build re-installs the packages afresh).

**Comment by van-nguyen** [comment]
Yeah I have moved it to peerDependency, hope that works for all.

**Comment by G-Rath** [comment]
@van-nguyen while it 'works', it's not really a good solution, for the reasons outlined in my last comment.

It's b/c of this that I'll likely be staying at v2.2.* for now, or even just forking the project and publishing my own version.

This is a great plugin, that I think is really cool, but ya there isn't any need to have babel running - just pick a version of node as a minimal targeted version (which is what most packages do - they tend to follow the LTS cycle employed by Node, providing support for the oldest version of Node Node themselves support), and build for that before publishing.

Saves us having to have babel installed every time.

For perspective: 
* `@babel/core` is `776.5kB`, with 14 dependencies.
* `@babel/cli` is `0.2kb`, with 10 dependencies.
* `@babel/preset-env` is `1200kB`, with 41 dependencies. 

* `webpack-cdn-plugin` is `3.2kB`, with 1 dependency.

This is all not counting peerDependencies. This means that your `3.2kb` package has us download **2 megabytes** of extra packages - **65** extra packages - just to have it installed. Once the package is installed, those extra packages are not used *at all*.

While that not might seem like much in terms of space on your average computer harddrive, in terms of your average package size, thats a lot - especially when you're having to install those packages on an average of 100 times a day, given `npm ci` is run for every CI build.

For contrast, `webpack` is `1.8mB`, `typescript` is `1.9mB`, & `react` is `5.9kB`.

Again, I **love** this plugin - it lets me chop out large chunks of my projects, reducing the size of my bundles by whole `mB`s, without my IDE or rest of my code knowing or having to care. It's *great*.

It's just also **bigger** than `typescript` and `webpack` right now, which is a bit of a high cost to have.

**Comment by QingWei-Li** [comment]
If we only support nodejs 5+, we don't need to compile it. 

Just fix the first line of code, it can run directly in the nodejs. 
https://github.com/van-nguyen/webpack-cdn-plugin/blob/97c1271b30282a91bd92061272dddfb8e3f71f74/module.js#L1


...I also face the same problem, and I don't want to install babel.😢

**Comment by van-nguyen** [comment]
Yeah this all makes sense, I guess back then people were on older node versions, now it seems more do-able if we drop all unsupported versions. I wiill try to get this sorted this weekend or PR is also welcome :)

**Pull request closed without merging**
