### PR TITLE
feat: add `crossorigin` attribute

### PR DESCRIPTION
**Pull request by myst729**
Feature requested in #14 , this PR is for v2.x.

### CODE REVIEW

**Comment by van-nguyen** [comment]
HI @myst729 okay now that I see this, is it possible to feature flag this? Not sure if we should force this to all assets.

**Comment by myst729** [comment]
Just made the option configurable, disabled by default. Readme updated.

The LTS of Node just jumped to version 10 so the travis process fails. Sorry for having pushed so many commits, please rebase with squash.

**Comment by myst729** [comment]
LTS of Node just jumped to version 10, which fails the CI process (https://travis-ci.org/van-nguyen/webpack-cdn-plugin/builds/449215521#L480). So I locked it to version 8, the previous LTS.

**Comment by van-nguyen** [comment]
Thanks for that, very nice. Will run couple more tests tonight before releasing on npm.

**Pull request merged**
