### PR TITLE
Refactor/remove babel

### PR DESCRIPTION
**Pull request by QingWei-Li**
I just replaced the ES module syntax and removed the babel deps and lint codes.

If CI passes, it proves that it can run on NodeJS 5+.

Discussed at #35

### CODE REVIEW

**Comment by QingWei-Li** [comment]
@van-nguyen 

`webpack-html-plugin` requires the lowest node version is 6.9. Maybe we don't need to support old versions. what do you think?

https://github.com/jantimon/html-webpack-plugin/blob/e2276195d2f919d68d0cffc5c0a7208bf27b010c/package.json#L72-L74

**Comment by van-nguyen** [comment]
Seems like they have probably recently added that engines property in, I guess we will have to follow. This makes the decision easier than.

**Comment by nicoabie** [comment]
Hi @van-nguyen, first of all thanks for this great plugin. It would be greater if you merge this pull request as there are many people out there that do not have babel installed and neither they are willing to.

I'm sure no one will complain.

This closes #45

**Comment by nicoabie** [comment]
@van-nguyen thanks!

**Comment by van-nguyen** [comment]
No probs, sorry I was missing in action for awhile..

**Pull request merged**
